title: Anastassios Nanos
url: "https://ananos.co.uk"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-1610214-7

footer: yes
footer_url: "https://github.com/ananos/ananos.github.io"
footer_text: "&copy; 2021 Anastassios Nanos, based on <a class=\"footer\" style=\"text-decoration: none;\" href=\"https://github.com/ankitsultana/ankitsultana.github.io\">ankitsultana</a>."

favicon: true
favicon_location: "images/favicon.png"

sass:
  style: compressed
  sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "Short Bio"
    link: "/short-bio"
  - name: "Resume"
    link: "/ananos-cv-en-20210212.pdf"
  - name: "Contact"
    link: "/contact"


